# Site settings
title: We get your ideas from zero to revenue | hacker.works
email: hi@hacker.works
description: > # this means to ignore newlines until "baseurl:"
  We are a team of full-stack hackers. We build prototypes, MVPs and scalable solutions by using the hacker mindset to overcome constraints.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hacker.works" # the base hostname & protocol for your site
exclude: [Gemfile, Gemfile.lock]
twitter_username: npacemo
github_username:  hacker-works
social_description: We are a team of full-stack hackers. We build prototypes, MVPs and scalable solutions by using the hacker mindset to overcome constraints.

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-assets

collections:
  careers:
    permalink: /careers/:path/
    output: true
